# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
permalink:           /:title/

# Setup
title:               Xorro P2P
tagline:             'An exercise in building a mini BitTorrent P2P network from scratch'
description:         'An exercise in building a mini BitTorrent P2P network from scratch'
url:                 'http://xorro-p2p.github.io'
baseurl:             ''

# About/contact
author:
  name:              
  url:               
  email:             

# Custom vars
version:             1.0.0
